require('myplugins/onedark')
require('myplugins.nvim-treesitter')
require('myplugins.flash')
require('myplugins.lspkind')
require('myplugins.mason-lspconfig')
require('myplugins.devicons')
require('myplugins.lualine')
require('myplugins.indent-blankline')
require('myplugins.telescope')
require('myplugins.fzf-lua')
require('myplugins.snacks')

require('myplugins.luasnip')
require('myplugins.blink-cmp')
require('myplugins.ts-autotag')
require('myplugins.rustaceanvim')
require('myplugins.refactoring')

require('myplugins.zk')
require('myplugins.conform')
require('myplugins.nvim-tree')
require('myplugins.mini')
