require('myplugins/lsp')
require('myplugins/nvim-treesitter')
require('myplugins/lspkind')
require('myplugins/lspsaga')
require('myplugins/devicons')
require('myplugins/chadtree')
require('myplugins/lualine')

require('myplugins/nvim-cmp')
require('myplugins/comment')
require('myplugins/autopairs')
require('myplugins/ts-autotag')
require('myplugins/gitsigns')
require('myplugins/nvim-test')
require('myplugins.rust-tools')

require('myplugins/zk')
