require('myplugins/onedark')
require('myplugins.nvim-treesitter')
require('myplugins.hop')
require('myplugins.flash')
require('myplugins.lspkind')
require('myplugins.mason-lspconfig')
require('myplugins.lspsaga')
require('myplugins.devicons')
require('myplugins.lualine')
require('myplugins.indent-blankline')
require('myplugins.telescope')
require('myplugins.fzf-lua')

require('myplugins.luasnip')
require('myplugins.blink-cmp')
require('myplugins.comment')
require('myplugins.autopairs')
require('myplugins.ts-autotag')
require('myplugins.gitsigns')
require('myplugins.dap')
require('myplugins.rust-tools')
require('myplugins.refactoring')

require('myplugins.zk')
require('myplugins.toggleterm')
require('myplugins.conform')
require('myplugins.nvim-tree')
require('myplugins.mini')
require('myplugins.neodev')
require('myplugins.render-markdown')

require('myplugins.dadbod')
